name: ChunkHoppers
version: 1.6
main: net.chunkhopper.src.Main
authors: [WeChanDoIt]
description: Adds a "Chunk Hopper" item that automatically collects all items in a chunk
commands:
  chunkhopper:
    description: Gives the specified player or command executor one or multiple chunkhoppers
    usage: /chunkhopper [amount] [player]
    permission: chunkhopper.give
    aliases: [retrohopper, hopper]
  retrochip:
    description: Gives the specified player or command executor one or multiple retrochips
    usage: /retrochip [amount] [player] [level]
    permission: chunkhopper.chips
    aliases: retrochips
  chunk:
    description: See an outline of the chunk you are in!
    usage: /chunk
    aliases: seechunk