name: Retrohopper
version: 1.4
main: net.retrohopper.src.Main
authors: [WeChanDoIt, Techied]
description: Adds a "Chunk Hopper" item that automatically collects all items in a chunk
depend: [SuperiorSkyblock2, WildStacker]
commands:
  retrohopper:
    description: Gives the specified player or command executor one or multiple RetroHoppers
    usage: /retrohopper [amount] [player]
    permission: retrohopper.give
    aliases: hopper
  retrochip:
    description: Gives the specified player or command executor one or multiple retrochips
    usage: /retrochip [amount] [player] [level]
    permission: retrohopper.chips
    aliases: retrochips
  chunk:
    description: See an outline of the chunk you are in!
    usage: /chunk
    aliases: seechunk